# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
# PURPOSE AND NONINFRINGEMENT.  In no event shall the ASF be liable for any
# claim, damages or other liability.
#
---
- name: "Stop Ozone cluster and clean directories"
  hosts: all
  gather_facts: false
  pre_tasks:
    - name: "Parse data_base into list"
      set_fact:
        data_base_list: "{{ ((data_base | default('')).split(',') | map('trim') | select | list) | default([data_base | default('/data/ozone')], true) }}"

    - name: "Parse metadata_base into list"
      set_fact:
        metadata_base_list: "{{ ((metadata_base | default(data_base) | default('')).split(',') | map('trim') | select | list) | default([metadata_base | default(data_base) | default('/data/ozone')], true) }}"

    - name: "Gather facts"
      setup:

  roles:
    - role: ozone_stop
      tags: ["ozone_stop", "cleanup"]
    - role: ozone_cleanup
      tags: ["cleanup"]
